development:
  adapter: redis

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:14cf267bb2bcd2e012f85e6ac4dfae8e@greeneye.redistogo.com:10589/
  channel_prefix: learn_enough_action_cable_production
